# Generated by Django 5.2.5 on 2025-12-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_router', '0004_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='disease_images/')),
                ('disease_class', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cropdisease',
            name='common_symptoms',
        ),
        migrations.RemoveField(
            model_name='cropdisease',
            name='prevention',
        ),
        migrations.RemoveField(
            model_name='cropdisease',
            name='risk_causes',
        ),
        migrations.RemoveField(
            model_name='cropdisease',
            name='spread',
        ),
        migrations.RemoveField(
            model_name='cropdisease',
            name='treatment',
        ),
        migrations.DeleteModel(
            name='Polygon',
        ),
        migrations.DeleteModel(
            name='UploadedImage',
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
        migrations.DeleteModel(
            name='PreventionMeasure',
        ),
        migrations.DeleteModel(
            name='RiskFactor',
        ),
        migrations.DeleteModel(
            name='SpreadMethod',
        ),
        migrations.DeleteModel(
            name='CropDisease',
        ),
        migrations.DeleteModel(
            name='TreatmentCure',
        ),
    ]
