# Generated by Django 5.2.5 on 2025-12-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_router', '0005_diseasedetection_remove_cropdisease_common_symptoms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasedetection',
            old_name='disease_class',
            new_name='disease_name',
        ),
        migrations.RenameField(
            model_name='diseasedetection',
            old_name='created_at',
            new_name='predicted_at',
        ),
        migrations.AddField(
            model_name='diseasedetection',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
